spring.application.name=moreeduce

# Database settings
spring.datasource.url=${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/moreeduce}
spring.datasource.username=${JDBC_DATABASE_USERNAME:postgres}
spring.datasource.password=${JDBC_DATABASE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Token Settings
token.signing.key=${TOKEN_SIGNING_KEY}
token.access.expiration=${TOKEN_ACCESS_EXPIRATION:86400000}
token.refresh.expiration=${TOKEN_REFRESH_EXPIRATION:259200000}

# MinIO Settings
minio.url=${MINIO_URL:http://localhost:9000}
minio.access.name=${MINIO_ACCESS_NAME:admin}
minio.access.secret=${MINIO_ACCESS_SECRET:admin12345}
minio.bucket.name=${MINIO_BUCKET_NAME:moreeduce}

# File Upload Limits
spring.servlet.multipart.max-file-size=150MB
spring.servlet.multipart.max-request-size=155MB

# Mail Settings - Gmail SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=zaripovmuxiddin4@gmail.com
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true


# AI Settings - Google Gemini
gemini.api.key=${GEMINI_API_KEY:}
gemini.api.url=${GEMINI_API_URL:}

# Render Deploy Fix
server.forward-headers-strategy=framework

# Exception Handling
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false

# Super Admin Default Credentials
app.super-admin.email=${SUPER_ADMIN_EMAIL}
app.super-admin.password=${SUPER_ADMIN_PASSWORD:superadmin123}